#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 22 13:51:56 2019
Script to read a textfile produced by a fluent UDF containing data from two planes 
appended over time with delimiters for each new timestep.
@author: gabgus
"""

import numpy as np
import h5py
import matplotlib.pyplot as plt
# -----------------------------------------------------------------------------
path = '/scratch/gabgus/fluent/henriks/noWall/planes/'


## interpolate the velocity of interest onto the created mesh
meshname='half'
elevation='high'
with h5py.File(path + 'plane_data.h5','r') as f:    
   maxN = f.attrs['last_no']
   xi = f['mesh'][meshname]['xi'][:]
   zi = f['mesh'][meshname]['zi'][:]
   vi = f[elevation][meshname]['xv'][0:maxN]
   t = f['time'][0:maxN]
#%%
#

plt.figure()
plt.contourf(xi,zi,vi[:].mean(axis=0),20,cmap='RdBu_r')
plt.colorbar()
#
## 11703,11955,11697
##  11688,11964,11694
#%%
n=5
vinst = vi[::n,7,25]
print(vinst.shape)

vbar = vinst.mean(axis=0)

vdot = vinst-vbar

print(np.mean(vdot**2))

def RL(kdot,vinst,vbar,vdot):
    top=0
    bot=0
    ksum=0
    
    if type(kdot) == 'int':
        kmax=kdot
    else:
        kmax=kdot[-1]
        
    for k in range(int(len(vinst) - kmax)):
        top = top + (vinst[k] - vbar)*(vinst[k+kdot] - vbar)
        bot  = bot+ (vinst[k] -vbar)**2
        ksum +=1
    
    top=top/ksum
    bot=bot/ksum
    
    return top/bot

N=int(maxN*0.3)#10050
karr=np.arange(int(N/n))

TL=np.trapz(RL(karr,vinst,vbar,vdot))

DT= np.mean(vdot**2)*TL

plt.figure()
plt.plot()
plt.plot(karr*n*5e-5,RL(karr,vinst,vbar,vdot))
plt.plot([karr[0]*n*5e-5,karr[-1]*n*5e-5],[0.0,0.0],'--k')
plt.title('$R_L$')
plt.xlabel('time [s]')
plt.grid()
DTlist=[]
Klist=[]
print(RL(karr[0:2],vinst,vbar,vdot))

for K in np.linspace(1,N/n):# 5000,6000,7000,8000,9000]:    
    karr=np.arange(int(K))
    TL=np.trapz(RL(karr,vinst,vbar,vdot),x=karr*n*5e-5)
    DT=np.mean(vdot**2)*TL
    DTlist.append(DT)
    Klist.append(K*5e-5*n)

plt.figure()
plt.plot(Klist,DTlist)
plt.title('$D_T$')
plt.xlabel('time lag [s]')



print(DTlist[-1])






